%.min.js : %.js
	echo "Arena/$@: JS compression"
	@yui-compressor --verbose --line-break 70 --charset UTF-8 -o $@ $<

all: \
	arena.min.js \
	skiniko.min.js \
	ego.min.js \
	tsoxa.min.js \
	efoplismos.min.js \
	aeras.min.js \
	dialogos.min.js \
	diataxi.min.js \
	kafinfo.min.js \
	profinfo.min.js \
	trapezi.min.js \
	sizitisi.min.js \
	kinisi.min.js \
	online.min.js \
	apanel.min.js \
	bpanel.min.js \
	cpanel.min.js \
	dpanel.min.js \
	epanel.min.js \
	kpanel.min.js \
	lpanel.min.js \
	mpanel.min.js \
	tpanel.min.js \
	zpanel.min.js
